# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YouTube_Downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pytube import YouTube



class Ui_YouTube_Downloader(object):
    def setupUi(self, YouTube_Downloader):
        YouTube_Downloader.setObjectName("YouTube_Downloader")
        YouTube_Downloader.setEnabled(True)
        YouTube_Downloader.resize(540, 422)
        YouTube_Downloader.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.centralwidget = QtWidgets.QWidget(YouTube_Downloader)
        self.centralwidget.setObjectName("centralwidget")
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(360, 70, 81, 21))
        self.search.setObjectName("search")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 330, 131, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(200, 330, 31, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.download = QtWidgets.QPushButton(self.centralwidget)
        self.download.setEnabled(True)
        self.download.setGeometry(QtCore.QRect(280, 330, 75, 23))
        self.download.setObjectName("download")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(50, 130, 411, 161))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.splitter)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setObjectName("textBrowser")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(30, 39, 431, 20))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.enter_url = QtWidgets.QLabel(self.splitter_2)
        self.enter_url.setAlignment(QtCore.Qt.AlignCenter)
        self.enter_url.setObjectName("enter_url")
        self.url = QtWidgets.QLineEdit(self.splitter_2)
        self.url.setText("")
        self.url.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.url.setObjectName("url")
        YouTube_Downloader.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(YouTube_Downloader)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName("menubar")
        YouTube_Downloader.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(YouTube_Downloader)
        self.statusbar.setObjectName("statusbar")
        YouTube_Downloader.setStatusBar(self.statusbar)
        self.label.setBuddy(self.textBrowser)
        self.enter_url.setBuddy(self.url)

        self.retranslateUi(YouTube_Downloader)
        self.search.clicked.connect(self.get_data) # type: ignore
        self.download.clicked.connect(self.get_file)
        QtCore.QMetaObject.connectSlotsByName(YouTube_Downloader)
        YouTube_Downloader.setTabOrder(self.url, self.search)
        YouTube_Downloader.setTabOrder(self.search, self.textBrowser)
        YouTube_Downloader.setTabOrder(self.textBrowser, self.lineEdit)
    
    def get_data(self):
        try:
            yt = YouTube(self.url.text())
            global videos
            videos = yt.streams.filter(adaptive = True)

            for video in videos:
                self.textBrowser.append(video, '-->', video[video])

        except:
            self.textBrowser.append('Connection ERROR!')
    
    def get_file(self):
        try:
            videos[self.lineEdit.text()].download()
        except:
            print('Something went wrong')
        print('Completed!')

    def retranslateUi(self, YouTube_Downloader):
        _translate = QtCore.QCoreApplication.translate
        YouTube_Downloader.setWindowTitle(_translate("YouTube_Downloader", "YouTube Downloader"))
        self.search.setText(_translate("YouTube_Downloader", "Search"))
        self.label_2.setText(_translate("YouTube_Downloader", "Enter the Chosen Number:"))
        self.download.setText(_translate("YouTube_Downloader", "Download"))
        self.label.setText(_translate("YouTube_Downloader", "Result:"))
        self.enter_url.setText(_translate("YouTube_Downloader", "Enter Your URL:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    YouTube_Downloader = QtWidgets.QMainWindow()
    ui = Ui_YouTube_Downloader()
    ui.setupUi(YouTube_Downloader)
    YouTube_Downloader.show()
    sys.exit(app.exec_())
